### ISSUE TITLE
If a html file as a canvas element,you will get an error.

### ISSUE THREAD

**Issue by vfan** [chrislondon/9-Patch-Image-for-Websites#19]
Uncaught TypeError: Failed to execute 'getComputedStyle' on 'Window': parameter 1 is not of type 'Element'.
in function NinePatchGetStyle, you may need to add try catch..
var computedStyle = window.getComputedStyle(element, "");

**Comment by Demian87** [comment]
I have the same issue. Do you have any ideas, how to fix it?

**Comment by rpendleton** [comment]
I'm not sure if this was the source of the original issue, but it appears the example was encountering this error due to the use of a `for...in` loop over an `HTMLContainer`. I've pushed a commit that should fix that along with a few other issues.

I also experimented with adding a `canvas` element to the document and didn't see any problems, so I'm going to assume the `for...in` loop was the cause of the original issue as well.

**Comment by Demian87** [comment]
That helped! Thanks!
